config/routes.rb
Rails.application.routes.draw do
  root to: "users#new"

  resources :users, only: [:new, :create, :show, :index] do
    resources :goals, only: [:index, :new]
  end

  resources :goals, only: [:create, :edit, :show, :update, :destroy]

  resource :session, only: [:new, :create, :destroy]

  resources :comments, only: :create
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :content, presence: true

  belongs_to :commentable, polymorphic: true
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  validates :title, :description, :status, :privacy, presence: true
  validates :status, inclusion: { in: %w(PENDING COMPLETED)}
  validates :privacy, inclusion: { in: %w(Public Private) }

  belongs_to :user, inverse_of: :goals

  has_many :comments, as: :commentable
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_reader :password

  validates :username, presence: true, uniqueness: true
  validates :password_digest, presence: true
  validates :password, length: { minimum: 6, allow_nil: true }

  after_initialize :ensure_session_token

  has_many :goals, inverse_of: :user

  has_many :comments, as: :commentable

  def self.find_by_credentials(username, password)
    user = User.find_by_username(username)
    user.try(:is_password?, password) ? user : nil
  end

  def self.generate_session_token!
    SecureRandom::urlsafe_base64(16)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def reset_session_token!
    self.session_token = User.generate_session_token!
    self.save!
    self.session_token
  end

  private

  def ensure_session_token
    self.session_token ||= User.generate_session_token!
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :logged_in?, :current_user

  def current_user
    return nil if session[:session_token].nil?
    user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login!(user)
    session[:session_token] = user.reset_session_token!
  end

  def logout!
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def require_logged_in
    unless logged_in?
      flash[:errors] = ['You must be logged in']
      redirect_to new_session_url
    end
  end

  def require_logged_out
    if logged_in?
      flash[:errors] = ['You are already logged in!']
      redirect user_url(current_user)
    end
  end

  def require_current_user
    unless session[:session_token] == current_user.session_token
      flash.now[:errors] = ['You cannot do this!']
      redirect_to user_goals_url(current_user)
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)

    if @comment.save
      redirect_to params[:url_param]
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to params[:comment][:url_param]
    end
  end

  def comment_params
    params.require(:comment).permit(:content, :user_id, :post_id)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  before_action :require_logged_in
  before_action :require_current_user, only: [:create, :edit, :update, :destroy]

  def index
    @goals = Goal.where(user_id: params[:user_id])
    @user = User.find(params[:user_id])
  end

  def new
    @goal = Goal.new
  end

  def show
    @goal = Goal.find(params[:id])
  end

  def create
    @goal = current_user.goals.new(goal_params)

    if @goal.save
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update(goal_params)
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to user_goals_url
  end

  private

  def goal_params
    params.require(:goal).permit(:title, :description, :status, :privacy, :user_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if @user.nil?
      flash.now[:errors] = ["Invalid username or password"]
      render :new
    else
      login!(@user)
      redirect_to user_goals_url(@user)
    end
  end

  def destroy
    logout!
    redirect_to new_session_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    render :new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login!(@user)
      redirect_to user_goals_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token
    <<-HTML.html_safe
      <input
      type="hidden"
      name="authenticity_token"
      value="#{form_authenticity_token}">
    HTML
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/_form.html.erb
<% action = ( @goal.persisted? ? goal_url(@goal) : goals_url )  %>
<% method_type = ( @goal.persisted? ? "PATCH" : "POST" ) %>

<form action="<%= action %>" method="POST">
  <input type="hidden" name="_method" value="<%= method_type %>">
  <%= auth_token %>

  <label for="title">Title</label> <br>
  <input type="text" name="goal[title]" value="<%= @goal.title %>" id="title">

  <br>

  <label for="description">Description</label> <br>
  <textarea id="description"
  name="goal[description]"><%= @goal.description %></textarea>

  <br>
  <label for="private">Private</label>
  <input type="radio" name="goal[privacy]" id="private"
  value="Private" <%= "selected" if "Private" == @goal.privacy %>>

  <label for="public">Public</label>
  <input type="radio" name="goal[privacy]" id="public"
  value="Public" <%= "selected" if "Public" == @goal.privacy %>>

  <input type="submit"
    value="<%= @goal.persisted? ? "Update Goal" : "Create Goal" %>">
</form>

app/views/goals/edit.html.erb
<h1>Edit Goal</h1>
<%= render "form" %>

app/views/goals/index.html.erb
<h1>All Goals for <%= @user.username %></h1>
<table>
  <tr>
    <th>Title</th>
    <th>Description</th>
    <th>Status</th>
    <th>Privacy</th>
    <th>Completed?</th>
    <th>Delete?</th>

  </tr>
<% @goals.each do |goal| %>
<tr>
  <td><a href="<%= goal_url(goal) %>"><%= goal.title %></a></td>
  <td><%= goal.description %></td>
  <td><%= goal.status %></td>
  <td><%= goal.privacy %></td>
  <td>
  <form action="<%= goal_url(goal) %>" method="POST">
    <%= auth_token %>
    <input type="hidden" name="_method" value="PATCH">
    <input type="hidden" name="goal[status]" value="COMPLETED">
    <input type="submit" value="Complete">
  </form>
  </td>
  <td>
    <form action="<%= goal_url(goal) %>" method="POST">
      <%= auth_token %>
      <input type="hidden" name="_method" value="DELETE">
      <input type="submit" value="Delete">
    </form>
  </td>
</tr>

<% end %>

</table>

<% @user.comments.each do |comment| %>
  <%= comment %>
  <%= comment.commentable %>
<% end %>

<br>
Add a comment
<form action="<%= comments_url %>" method="POST">
  <%= auth_token %>
  <input type="hidden" name="url_param" value="<%= user_goals_url(@user.id) %>">
  <textarea name="comment[content]"></textarea>
  <input type="submit" value="Add Comment">
</form>

<a href="<%= new_user_goal_url %>">Create Goal</a>
<br>

app/views/goals/new.html.erb
<h1>Create Goal</h1>
<%= render "form" %>

app/views/goals/show.html.erb
<h1><%= @goal.title %></h1>

<%= @goal.description %> <br>
<br>
<strong><%= @goal.status %></strong> <br>
<strong><%= @goal.privacy %></strong><br>
<br>
<a href="<%= edit_goal_url %>">Edit this Goal</a>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TodoList</title>
</head>
<body>
  <% if flash[:errors] %>
  <ul>
    <% flash[:errors].each do |error| %>
    <li><%= error %></li>
    <% end %>
  </ul>
  <% end %>
<%= yield %>

<hr>

<% if logged_in? %>
  <a href="<%= user_goals_url(current_user) %>">&lt;&lt;Back to Goal Index</a><br>
You are logged in as <%= current_user.username %>
  <form action="<%= session_url %>" method="POST">
    <%= auth_token %>
    <input type="hidden" name="_method" value="DELETE">
    <input type="submit" value="Log Out">
  </form>
<% else %>
  <form action="<%= new_user_url %>" method="GET">
    <%= auth_token %>
    <input type="submit" value="Register">
  </form>
  <form action="<%= new_session_url %>" method="GET">
    <%= auth_token %>
    <input type="submit" value="Sign In">
  </form>
<% end %>
</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="POST">
  <%= auth_token %>
  <label for="username">Username</label>
  <input type="text" name="user[username]" id="username">

  <label for="password">Password</label>
  <input type="password" name="user[password]" id="password">

  <input type="submit" value="Sign Up">
</form>